### ISSUE TITLE
Exporter Failed to retrieve java process list

### ISSUE THREAD

**Issue by v703612** [banzaicloud/.github#2]
Dear,

Since few days we are trying to connect the jmx exporter operator to our kubernetes instance, but we are currently having issues that we have (see screenshot). Could we add extra logging or have you any idea how we can continue?
![image](https://user-images.githubusercontent.com/26733848/85257445-2a720200-b466-11ea-984f-80b07c30d3a7.png)

**Comment by sagikazarmark** [comment]
This doesn't seem to be the right place.
